### ISSUE TITLE
Unable to load 'webpack-cli/serve' command on default app

### ISSUE THREAD

**Issue by lopezm94** [dfinity/sdk#1889]
After following the [instructions](https://sdk.dfinity.org/docs/quickstart/local-quickstart.html) for the quickstart guide of the hello app I got to this error.

```
$ npm start               

> hello_assets@0.1.0 prestart
> npm run copy:types


> hello_assets@0.1.0 copy:types
> rsync -avr .dfx/$(echo ${DFX_NETWORK:-'**'})/canisters/** --exclude='assets/' --exclude='idl/' --exclude='*.wasm' --delete src/declarations

building file list ... done

sent 310 bytes  received 20 bytes  660.00 bytes/sec
total size is 19112  speedup is 57.92

> hello_assets@0.1.0 start
> webpack serve --mode development --env development

[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
```

It was solved by changing 'webpack-cli' version from "4.5.0" to "4.9.1". Not a serious issue but might be helpful for new comers. This issue was found on MacOS with a M1 chipset.

If increasing the version doesn't cause any issues I would gladly create a PR.

**Comment by krpeacock** [comment]
I've updated the version in #1916 . We've still seen issues with the proxy not connecting, which you may be able to resolve by upgrading to Node 16. It's an issue with the proxy tool that Webpack using under the hood, and there's unfortunately not much we can do about it. 

This should be resolved when dfx 0.8.4 comes out though!

**Comment by WowDarkHole** [comment]
My dfx version is 0.9.2
and The webpack version is 4.9.1.
But I'm still getting that error..

arthas@ubuntu:~/Documents/ICP/hello$ npm start

> hello_assets@0.1.0 prestart /home/arthas/Documents/ICP/hello
> npm run copy:types


> hello_assets@0.1.0 copy:types /home/arthas/Documents/ICP/hello
> rsync -avr .dfx/$(echo ${DFX_NETWORK:-'**'})/canisters/** --exclude='assets/' --exclude='idl/' --exclude='*.wasm' --delete src/declarations

sending incremental file list

sent 338 bytes  received 14 bytes  704.00 bytes/sec
total size is 19,126  speedup is 54.34

> hello_assets@0.1.0 start /home/arthas/Documents/ICP/hello
> webpack serve --mode development --env development

No production canister_ids.json found. Continuing with local
<i> [webpack-dev-server] [HPM] Proxy created: /api  -> http://localhost:8000
<i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/api" ~> "/api"
[webpack-cli] /home/arthas/Documents/ICP/hello/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/home/arthas/Documents/ICP/hello/node_modules/webpack-dev-server/lib/Server.js:1663:28)
    at Server.createWebSocketServer (/home/arthas/Documents/ICP/hello/node_modules/webpack-dev-server/lib/Server.js:2443:57)
    at Server.start (/home/arthas/Documents/ICP/hello/node_modules/webpack-dev-server/lib/Server.js:3229:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! hello_assets@0.1.0 start: `webpack serve --mode development --env development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the hello_assets@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arthas/.npm/_logs/2022-03-06T13_36_43_627Z-debug.log

**Comment by krpeacock** [comment]
This is a bug with the Webpack proxy plugin and Node 17. Switching to node 16 should solve the issue

**Comment by Pepn** [comment]
Getting the same issue using WSL and a fresh install:

`No production canister_ids.json found. Continuing with local
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function`

**Comment by George-Olufemi** [comment]
Getting a similar error and don't know how to fix it, what do i do?

npm start

> hello_assets@0.1.0 prestart
> npm run copy:types


> hello_assets@0.1.0 copy:types
> rsync -avr .dfx/$(echo ${DFX_NETWORK:-'**'})/canisters/** --exclude='assets/' --exclude='idl/' --exclude='*.wasm' --exclude='*.most' --delete src/declarations

building file list ... done

sent 266 bytes  received 20 bytes  572.00 bytes/sec
total size is 19112  speedup is 66.83

> hello_assets@0.1.0 start
> webpack serve --mode development --env development

No production canister_ids.json found. Continuing with local
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (/Users/georgeolufemi/Documents/Web3-ICP/hello/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/georgeolufemi/Documents/Web3-ICP/hello/node_modules/webpack-cli/lib/webpack-cli.js:1672:7)

**Comment by apecollector** [comment]
Same issue following the quick start:

```sh
$ npm start



> hello_assets@0.1.0 prestart
> npm run copy:types


> hello_assets@0.1.0 copy:types
> rsync -avr .dfx/$(echo ${DFX_NETWORK:-'**'})/canisters/** --exclude='assets/' --exclude='idl/' --exclude='*.wasm' --exclude='*.most' --delete src/declarations

building file list ... done

sent 304 bytes  received 20 bytes  648.00 bytes/sec
total size is 19101  speedup is 58.95

> hello_assets@0.1.0 start
> webpack serve --mode development --env development

No production canister_ids.json found. Continuing with local
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (/Development/crypto/icp/hello/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Development/crypto/icp/hello/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```

**Comment by suenalaba** [comment]
Had the same issue. [apecollector](https://github.com/apecollector)'s solution worked for me. Upgraded from "4.9.1" to "webpack-cli": "4.10.0"

**Comment by serethewind** [comment]
> Same issue following the quick start:
> 
> ```shell
> $ npm start
> 
> 
> 
> > hello_assets@0.1.0 prestart
> > npm run copy:types
> 
> 
> > hello_assets@0.1.0 copy:types
> > rsync -avr .dfx/$(echo ${DFX_NETWORK:-'**'})/canisters/** --exclude='assets/' --exclude='idl/' --exclude='*.wasm' --exclude='*.most' --delete src/declarations
> 
> building file list ... done
> 
> sent 304 bytes  received 20 bytes  648.00 bytes/sec
> total size is 19101  speedup is 58.95
> 
> > hello_assets@0.1.0 start
> > webpack serve --mode development --env development
> 
> No production canister_ids.json found. Continuing with local
> [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
>     at Command.<anonymous> (/Development/crypto/icp/hello/node_modules/@webpack-cli/serve/lib/index.js:146:35)
>     at async Promise.all (index 1)
>     at async Command.<anonymous> (/Development/crypto/icp/hello/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
> ```
> 
> Edit: Updating webpack version to `4.10.0` in the `package.json` and running `npm install` fixed the issue.
> 
> Related issue from webpack repo: [webpack/webpack#15951](https://github.com/webpack/webpack/issues/15951)

Updating to 4.10.0 resolved the issue. Thansk @apecollector

**Comment by rishabhsharawat15** [comment]
problem solved by updating  
>**"webpack-cli"**: "4.10.0";  from "webpack-cli": "4.9.2";
>{ npm install } to update 
>{npm start}

**Comment by NicolasGula** [comment]
I have the same problem today September 20 of 2022. 
Upgrade webpack-cli 4.9 to 4.10.

**Comment by kamalcou** [comment]
npm install webpack-cli@4.10.0 

this command works for me.

**Comment by redolfosei** [comment]
I used nvm to install node LTS
cd into the project folder
used command: npm install webpack-cli@4.10.0

solved the error.

**Comment by abhi763153** [comment]
Getting a similar error and don't know how to fix it, what do i do? 
I am using  dfx 0.9.3, node v16.19.1 and webpack-cli 4.10.0
Please help me to get this resolved.

abhi763153@DESKTOP-6EN0Q8Q:~/ic-projects/hello$ dfx --version
dfx 0.9.3
abhi763153@DESKTOP-6EN0Q8Q:~/ic-projects/hello$ node --version
v16.19.1
"webpack-cli": "^4.10.0"

>npm start
> hello_assets@0.1.0 prestart
> npm run copy:types


> hello_assets@0.1.0 copy:types
> rsync -avr .dfx/$(echo ${DFX_NETWORK:-'**'})/canisters/** --exclude='assets/' --exclude='idl/' --exclude='*.wasm' --exclude='*.most' --delete src/declarations

sending incremental file list

sent 321 bytes  received 14 bytes  670.00 bytes/sec
total size is 19,112  speedup is 57.05

> hello_assets@0.1.0 start
> webpack serve --mode development --env development

No production canister_ids.json found. Continuing with local
<i> [webpack-dev-server] [HPM] Proxy created: /api  -> http://localhost:8000
<i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/api" ~> "/api"
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8081/
<i> [webpack-dev-server] On Your Network (IPv4): http://172.21.93.160:8081/
<i> [webpack-dev-server] Content not from webpack is served from '/home/abhi763153/ic-projects/hello/public' directory
asset index.js 837 KiB [emitted] (name: index) 1 related asset
asset logo.png 24.8 KiB [emitted] [from: src/hello_assets/assets/logo.png] [copied]
asset favicon.ico 15 KiB [emitted] [from: src/hello_assets/assets/favicon.ico] [copied]
asset index.html 663 bytes [emitted]
asset main.css 537 bytes [emitted] [from: src/hello_assets/assets/main.css] [copied]
asset sample-asset.txt 24 bytes [emitted] [from: src/hello_assets/assets/sample-asset.txt] [copied]
runtime modules 27.1 KiB 13 modules
modules by path ./node_modules/ 704 KiB
  modules by path ./node_modules/@dfinity/ 234 KiB 38 modules
  modules by path ./node_modules/webpack-dev-server/client/ 55.8 KiB 12 modules
  modules by path ./node_modules/borc/ 113 KiB 10 modules
  modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
  modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
  modules by path ./node_modules/simple-cbor/src/*.js 17.5 KiB 3 modules
  modules by path ./node_modules/iso-url/ 4.36 KiB 3 modules
modules by path ./src/ 2.05 KiB
  ./src/hello_assets/src/index.js 526 bytes [built] [code generated]
  ./src/declarations/hello/index.js 1.38 KiB [built] [code generated]
  ./src/declarations/hello/hello.did.js 167 bytes [built] [code generated]
webpack 5.63.0 compiled successfully in 1410 ms

**Comment by akaashvandanapu** [comment]
Same issue for me as @abhi763153 please help!!

**Comment by waran2337** [comment]
cal
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (/home/waran/ic-projects/hello/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/home/waran/ic-projects/hello/node_modules/webpack-cli/lib/webpack-cli.js:1672:7)


also had same issue.
after changing "webpack-cli": "4.10.0", in package.json --- save it---- and Run ----- npm install ------ then---- npm start
this would work!!!!
